// Copyright 2016 Attic Labs, Inc. All rights reserved.
// Licensed under the Apache License, version 2.0:
// http://www.apache.org/licenses/LICENSE-2.0

module.exports = {
  'parser': 'babel-eslint',
  'rules': {
    'array-bracket-spacing': ['error', 'never'],
    'arrow-body-style': ['error', 'as-needed'],
    'arrow-parens': 0,
    'arrow-spacing': ['error', {'before': true, 'after': true}],
    'camelcase': 'error',
    'comma-dangle': ['error', 'always-multiline'],
    'comma-spacing': ['error', {'before': false, 'after': true}],
    'eol-last': 'error',
    'eqeqeq': 'error',
    'flowtype/boolean-style': 'error',
    'flowtype/define-flow-type': 1,
    'flowtype/use-flow-type': 1,
    'flowtype/delimiter-dangle': ['error', 'always-multiline'],
    'flowtype/generic-spacing':  ['error', 'never'],
    'flowtype/semi':  ['error', 'always'],
    // Does not work with newlines: https://github.com/gajus/eslint-plugin-flowtype/issues/31
    // 'flowtype/space-after-type-colon':  ['error', 'always'],
    // 'flowtype/space-before-type-colon':  ['error', 'never'],
    'flowtype/space-before-generic-bracket':  ['error', 'never'],
    'flowtype/union-intersection-spacing':  ['error', 'always'],
    'indent': ['error', 2, {'SwitchCase': 1}],
    'keyword-spacing': 'error',
    'linebreak-style': ['error', 'unix'],
    'max-len': ['error', 100, 8],
    'no-fallthrough': 'error',
    'no-multi-spaces': 'error',
    'no-new-wrappers': 'error',
    'no-throw-literal': 'error',
    'no-trailing-spaces': 'error',
    'no-unused-vars': ['error', {'argsIgnorePattern': '^_$', 'varsIgnorePattern': '^_$'}],
    'no-var': 'error',
    'object-curly-spacing': ['error', 'never'],
    'prefer-arrow-callback': 'error',
    'prefer-const': 'error',
    'quotes': ['error', 'single'],
    'require-yield': 'error',
    'radix': 'error',
    'react/jsx-no-duplicate-props': 'error',
    'react/jsx-no-undef': 'error',
    'react/jsx-uses-react': 'error',
    'react/jsx-uses-vars': 'error',
    'semi': 'error',
    'space-before-function-paren': 0,
    'space-in-parens': ['error', 'never'],
    'space-infix-ops': 'error',
  },
  'env': {
    'es6': true,
    'node': true,
    'browser': true,
  },
  'extends': 'eslint:recommended',
  'ecmaFeatures': {
    'jsx': true,
    'experimentalObjectRestSpread': true,
  },
  'plugins': [
    'flowtype',
    'react',
  ],
};
