package types

// The methods for these types are generated by a tool.
// See http://clipperhouse.github.io/gen.

// +gen value
type Bool bool

// +gen value
type Int16 int16

// +gen value
type Int32 int32

// +gen value
type Int64 int64

// +gen value
type UInt16 uint16

// +gen value
type UInt32 uint32

// +gen value
type UInt64 uint64

// +gen value
type Float32 float32

// +gen value
type Float64 float64
