// Generated by: main
// TypeWriter: noms
// Directive: +gen on UInt16

package types

// DO NOT EDIT
//
// This file was generated by a tool.
// See http://clipperhouse.github.io/gen for details.

func (self UInt16) Equals(other Value) bool {
	if other, ok := other.(UInt16); ok {
		return self == other
	} else {
		return false
	}
}
