// This file was generated by nomdl/codegen.
// @flow
// eslint-disable max-len

import * as _noms from '@attic/noms';

{
  const pkg = new _noms.Package([
    _noms.makeStructType('S',
      [
        new _noms.Field('s', _noms.stringType, false),
        new _noms.Field('b', _noms.boolType, false),
      ],
      [

      ]
    ),
    _noms.makeEnumType('E', 'e1', 'e2', 'e3'),
  ], [
  ]);
  _noms.registerPackage(pkg);
}


export interface S extends _noms.Struct {
  s: string;  // readonly
  setS(value: string): S;
  b: boolean;  // readonly
  setB(value: boolean): S;
}

export type E =
  0 |  // e1
  1 |  // e2
  2;  // e3
