#!/bin/bash

set -e

bats \
    merge-3way-schema-changes.bats \
    merge-base.bats \
    merge.bats \
    migrate.bats \
    migration-integration.bats \
    multidb.bats \
    multiple-tables.bats \
    no-repo.bats \
    primary-key-changes.bats \
    query-catalog.bats \
    regression-tests.bats \
    remotes-aws.bats \
    remotes-file-system.bats \
    remotes-localbs.bats \
    remotes-sql-server.bats \
    remotes.bats \
    remotesrv.bats \
    rename-tables.bats \
    replace.bats \
    replication-multidb.bats \
    replication.bats \
    reset.bats \
    revert.bats \
    schema-changes.bats \
    schema-export.bats \
    schema-import.bats \
    send-metrics.bats \
    sql-add.bats \
    sql-backup.bats \
    sql-batch.bats \
    sql-branch.bats \
    sql-charsets-collations.bats \
    sql-check-constraints.bats \
    sql-checkout.bats \
    sql-clean.bats \
    sql-client.bats \
    sql-commit.bats \
    sql-config.bats \
    sql-conflicts-resolve.bats \
    sql-conflicts.bats \
    sql-create-database.bats \
    sql-create-tables.bats \
    sql-diff.bats \
    sql-fetch.bats \
    sql-load-data.bats \
    sql-merge.bats \
    sql-multi-db.bats \
    sql-privs.bats \
    sql-pull.bats \
    sql-push.bats \
    sql-reserved-column-name.bats \
    sql-reset.bats \
    sql-server-remotesrv.bats \
    sql-server.bats \
    sql-shell.bats \
    sql-show.bats \
    sql-spatial-types.bats \
    sql-status.bats \
    sql-tags.bats \
    sql.bats \
    status.bats \
    system-tables.bats \
    tableplus.bats \
    triggers.bats \
    types.bats \
    validation.bats \
    verify-constraints.bats \
    window.bats
