// Copyright 2026 Dolthub, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package sequences

import (
	"context"

	"github.com/dolthub/go-mysql-server/sql"
)

// This package is a collection of interfaces that describe state machines that are controlled by the global state.
// It is a separate package from the parent package globalstate so that doltdb can depend on it.

// A SequenceState is an incrementing state that must be shared across all branches and transactions.
// It corresponds to a table or root object in the database.
// |Self| should always be the same type as the implementation.
// It produces a sequence of |ValueType| each time Next() is called.
type SequenceState[Self any, ValueType comparable] interface {
	// Next advances the state of the sequence, producing a SQL value and the next SequenceState.
	Next() (sqlVal ValueType, hasNext bool, nextState Self, err error)
	// CurrentValue returns the next SQL value in the sequence without advancing it.
	CurrentValue() (sqlVal ValueType)
	// WithValue sets the state such that the next SQL value will be the one provided, then returns the new SequenceState.
	WithValue(sqlVal ValueType) Self
	// WithSQLValue coerces the input into the required type, then sets the state such that the next SQL value will be the one provided, then returns the new SequenceState.
	WithSQLValue(ctx *sql.Context, v interface{}) (Self, error)
	// GreaterThan compares two states and determines which one has advanced further.
	GreaterThan(other Self) bool
	// AtEnd returns whether the sequence is at its end. If true, then subsequent calls to SequenceState will
	// no longer advance the sequence and may return an error.
	AtEnd() bool
	// Merge combines two states, usually returning the one that's further along. If the states can't be combined,
	// |ok| is false.
	Merge(other Self) (merged Self, ok bool)
}

// A SequencedRelation is a table or root object with a state that must be shared across all branches
// and transactions in order to ensure global uniqueness of created rows. It wraps a SequenceState.
// Because some implementations are immutable (doltdb.Table), the methods that set the state must return a new
// value instead of self-mutating.
type SequencedRelation[Self any, ValueType comparable, StateType SequenceState[StateType, ValueType]] interface {
	// GetSequenceState returns the current SequenceState of the object.
	GetSequenceState(ctx context.Context) (StateType, error)
	// HasSequenceState returns whether the relation wraps a sequence.
	// (This may be false, for instance, for tables that do not have an AUTO INCREMENT column)
	HasSequenceState(ctx context.Context) (bool, error)
	// GetSequenceSqlType returns the SQL type generated by the sequence.
	GetSequenceSqlType(ctx context.Context) (sql.Type, bool, error)
	// SetSequenceState unconditionally sets the SequenceState for the object.
	SetSequenceState(ctx context.Context, val StateType) (Self, error)
	// TrySetSequenceState attempts to set the SequenceState for the object, but may fail if the provided state is
	// incompatible with the other state of the object. Returns a bool indicating success.
	// (For example, setting a table's AUTO INCREMENT value to be less than a value currently written to the table will fail.)
	TrySetSequenceState(ctx *sql.Context, val StateType) (Self, bool, error)
}
