name: Bump Dolt on Homebrew

on:
  repository_dispatch:
    types: [ bump-homebrew ]

jobs:
  homebrew-bump:
    name: Bump Dolt Homebrew formula
    runs-on: ubuntu-22.04
    steps:
      - name: Create Homebrew PR
        uses: mislav/bump-homebrew-formula-action@v2.1
        if: ${{ github.event_name == 'repository_dispatch' }}
        with:
          formula-name: dolt
          tag-name: ${{format('refs/tags/v{0}', github.event.client_payload.version)}}
        env:
          COMMITTER_TOKEN: ${{secrets.REPO_ACCESS_TOKEN}}
