name: Check Compatibility

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'go/**'
      - 'integration-tests/**'

concurrency:
  group: ci-compatibility-tests-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Compatibility Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-22.04 ]
    steps:
      - uses: actions/checkout@v6
      - name: Set up Go toolchain
        uses: ./.github/actions/setup-go-toolchain
      - uses: actions/setup-node@v4
        with:
          node-version: ^16
      - name: Install netcat
        run: sudo apt-get update && sudo apt-get install -y netcat-openbsd
      - name: Build dolt
        uses: ./.github/actions/build-dolt
      - name: Install Bats
        run: |
          npm i bats
          echo "$(pwd)/node_modules/.bin" >> $GITHUB_PATH
        working-directory: ./.ci_bin
      - name: Setup Dolt Config
        uses: ./.github/actions/setup-dolt-config
      - name: Test all
        run: ./runner.sh
        working-directory: ./integration-tests/compatibility
