name: Race tests

on:
  push:
    branches: [ main ]
    paths:
      - 'go/**'
  workflow_dispatch:

jobs:
  racetests:
    name: Go race tests
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04 ]
        dolt_fmt: [ "__DOLT__" ]
        adaptive_encoding: [ "false", "true" ]
    steps:
    - uses: actions/checkout@v6
    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version-file: go/go.mod
      id: go
    - name: Generate coverage package list
      working-directory: ./go/cmd/dolt
      run: |
        go list -f '{{if not .Standard}}{{.ImportPath}}{{end}}' -deps . | grep dolthub | paste -sd"," - > "$GITHUB_WORKSPACE/pkgs.txt"
    - name: Create coverage directory
      run: |
        mkdir -p /tmp/coverdata/race
        echo "GOCOVERDIR=/tmp/coverdata/race" >> $GITHUB_ENV
    - name: Test engine
      working-directory: ./go
      run: |
        COV_PKGS=$(cat "$GITHUB_WORKSPACE/pkgs.txt")
        DOLT_SKIP_PREPARED_ENGINETESTS=1 go test -cover -coverpkg="$COV_PKGS" -vet=off -v -race -timeout 30m github.com/dolthub/dolt/go/libraries/doltcore/sqle/enginetest -args -test.gocoverdir=/tmp/coverdata/race
      env:
        DOLT_DEFAULT_BIN_FORMAT: ${{ matrix.dolt_fmt }}
        DOLT_USE_ADAPTIVE_ENCODING: ${{ matrix.adaptive_encoding }}
    - name: Test concurrentmap
      working-directory: ./go
      run: |
        COV_PKGS=$(cat "$GITHUB_WORKSPACE/pkgs.txt")
        go test -cover -coverpkg="$COV_PKGS" -vet=off -v -race -timeout 1m github.com/dolthub/dolt/go/libraries/utils/concurrentmap -args -test.gocoverdir=/tmp/coverdata/race
      env:
        DOLT_USE_ADAPTIVE_ENCODING: ${{ matrix.adaptive_encoding }}
    - name: Upload coverage data
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-race-${{ matrix.adaptive_encoding }}
        path: /tmp/coverdata
        retention-days: 5
