name: sql-server Integration Tests

on:
  pull_request:
    branches: [main]
    paths:
      - "go/**"
      - "integration-tests/go-sql-server-driver/**"

concurrency:
  group: ci-sql-server-integration-tests-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: sql-server Integration Tests
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04]
        adaptive_encoding: ["false", "true"]
    steps:
      - uses: actions/checkout@v6
      - name: Setup Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: go/go.mod
        id: go
      - name: Create CI Bin
        run: |
          mkdir -p ./.ci_bin
      - name: Generate coverage package list
        working-directory: ./go/cmd/dolt
        run: |
          go list -f '{{if not .Standard}}{{.ImportPath}}{{end}}' -deps . | grep dolthub | paste -sd"," - > "$GITHUB_WORKSPACE/pkgs.txt"
      - name: Create coverage directory
        run: |
          mkdir -p /tmp/coverdata/sql-server
          echo "GOCOVERDIR=/tmp/coverdata/sql-server" >> $GITHUB_ENV
      - name: Install Dolt
        working-directory: ./go
        run: |
          COV_PKGS=$(cat "$GITHUB_WORKSPACE/pkgs.txt")
          go build -cover -coverpkg="$COV_PKGS" -mod=readonly -o ../.ci_bin/dolt ./cmd/dolt/
      - name: Test all
        run: |
          export DOLT_BIN_PATH="$(pwd)/../../.ci_bin/dolt"
          go test .
        working-directory: ./integration-tests/go-sql-server-driver
        env:
          DOLT_USE_ADAPTIVE_ENCODING: ${{ matrix.adaptive_encoding }}
      - name: Upload coverage data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-sql-server-${{ matrix.adaptive_encoding }}
          path: /tmp/coverdata
          retention-days: 5
