name: sql-server Integration Tests

on:
  pull_request:
    branches: [main]
    paths:
      - "go/**"
      - "integration-tests/go-sql-server-driver/**"

concurrency:
  group: ci-sql-server-integration-tests-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: sql-server Integration Tests
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v6
      - name: Set up Go toolchain
        uses: ./.github/actions/setup-go-toolchain
      - name: Build dolt
        uses: ./.github/actions/build-dolt
      - name: Test all
        run: go test .
        working-directory: ./integration-tests/go-sql-server-driver
