name: Import Benchmarks
on:
  workflow_dispatch:
    inputs:
      email_recipient:
        description: 'email to send results report to'
        rquired: false
        default: 'max@dolthub.com'
      version:
        description: 'dolt version to checkout'
        rquired: false
        default: ''
      run_file:
        description: 'import perf .yaml spec, relative to `import_benchmarks/testdata`'
        rquired: false
        default: 'ci.yaml'
      report:
        description: 'reporting query, relative to `import_benchmarks/reporting`'
        rquired: false
        default: 'three_way_compare.sql'
env:
  BENCH_DIR: 'go/performance/import_benchmarker'
  MYSQL_PORT: 3309
  MYSQL_PASSWORD: password
jobs:
  bench:
    name: Benchmark
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      id: go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.19

    - name: Dolt version
      id: version
      run: |
        version=${{ github.event.inputs.version }}
        if [ -z "$version" ]; then
            version=${{ github.sha }}
        fi
        echo "::set-output name=ref::$version"

    - uses: actions/checkout@v3
      with:
        ref: ${{ steps.version.outputs.ref }}

    - name: Install dolt
      working-directory: ./go
      run: go install ./cmd/dolt

    - uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: '8.0'
        auto-start: true
        root-password: ${{ env.MYSQL_PASSWORD }}
        my-cnf: |
          local_infile=1
          socket=/tmp/mysqld2.sock
          port=${{ env.MYSQL_PORT }}

    - name: Setup MySQL
      run: mysql -uroot -p${{ env.MYSQL_PASSWORD }} -h127.0.0.1 -P${{ env.MYSQL_PORT }} -e 'create database test;'

    - name: Run bench
      id: bench
      working-directory: go/
      run: |
        out="$GITHUB_WORKSPACE/results.sql"
        testspec="../${{ env.BENCH_DIR }}/testdata/${{ github.event.inputs.run_file }}"
        go run \
          "github.com/dolthub/dolt/${{ env.BENCH_DIR }}/cmd" \
          -test "$testspec" \
          -out "$out"
        echo "::set-output name=result_path::$out"

    - name: Report
      id: report
      run: |
        gw=$GITHUB_WORKSPACE
        in="${{ steps.bench.outputs.result_path }}"
        query="$(pwd)/${{ env.BENCH_DIR }}/reporting/${{ github.event.inputs.report }}"
        out="$gw/results.csv"

        mkdir "$gw/res"
        cd "$gw/res"

        dolt config --global --add user.email "max@dolthub.com"
        dolt config --global --add user.name "Max Hoffman"

        dolt init
        dolt sql < "$in"
        dolt sql -r csv < "$query" > "$out"

        cat "$out"
        echo "::set-output name=report_path::$out"

    - name: Format HTML
      id: html
      run: |
        gw="$GITHUB_WORKSPACE"
        in="${{ steps.report.outputs.report_path }}"
        out="$gw/results.html"

        echo "<table>" > "$out"
        print_header=true
        while read line; do
          if "$print_header"; then
            echo "  <tr><th>${line//,/</th><th>}</th></tr>" >> "$out"
            print_header=false
            continue
          fi
          echo "  <tr><td>${line//,/</td><td>}</td></tr>" >> "$out"
        done < "$in"
        echo "</table>" >> "$out"

        cat "$out"

        echo "::set-output name=html::$(echo $out)"

    - name: Format template
      id: template
      uses: mikefarah/yq@master
      with:
        cmd: |
          yq -o=json <<EOF
          Template:
            TemplateName: ImportBenchmarkingReleaseTemplate
            SubjectPart: Import Benchmarks for {{format}} {{version}}
            HtmlPart: |
              <!DOCTYPE html>
              <html lang="en">
              <head>
               <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Dolt {{format}} {{version}} Import Results</title>
                <style>
                  table {
                    border: 1px solid black;
                    letter-spacing: 1px;
                    font-family: sans-serif;
                    font-size: .8rem;
                    padding: 5px;
                    margin: 5px;
                  }
                  th {
                    border: 1px solid rgb(190, 190, 190);
                    padding: 10px;
                  }
                  td {
                    padding: 5px;
                  }
                  tr:nth-child(even) {
                    background-color: #f2f2f2;
                  }
               </style>
              </head>
                <body>{{results}}</body>
              </html>
          EOF

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: echo template
      id: template_file
      run: |
        out=$GITHUB_WORKSPACE/template.json
        echo '${{ steps.template.outputs.result }}' >> "$out"
        echo "::set-output name=result::$out"

    - name: Get Addresses
      id: email_addr
      env:
        RECIPIENT: ${{ github.event.inputs.email_recipient }}
        TEAM: '["${{ secrets.PERF_REPORTS_EMAIL_ADDRESS }}"]'
      run: |
        addresses="$TEAM"
        if [ ! -z "$RECIPIENT" ]; then
          addresses="[\"$RECIPIENT\"]"
        fi
        echo "::set-output name=addresses::$addresses"

    - name: Send Email
      uses: ./.github/actions/ses-email-action
      with:
        region: us-west-2
        toAddresses: ${{ steps.email_addr.outputs.addresses }}
        version: ${{ steps.version.outputs.ref }}
        format: '__DOLT__'
        dataFile: ${{ steps.html.outputs.html }}

    - name: Dolt Import
      uses: dolthub/dolt-action@v0.16
      id: 'dolt_import'
      with:
        remote: max-hoffman/import-perf
        dolthub_credential: ${{ secrets.DOLTHUB_CREDENTIAL }}
        commit_message: 'automated CI commit'
        commit_user_email: 'max@dolthub.com'
        commit_author: 'Max Hoffman'
        branch: main
        push: true
        before: |
          dolt sql -b -q <<EOF
          call dolt_checkout('-b', '${{ steps.version.outputs.ref }}');
          drop table if exists import_perf_results;
          EOF

          in="${{ steps.bench.outputs.result_path }}"
          dolt sql < "$in"

