name: Label Customer Issues

on:
  issues:
    types: [opened]
  pull_request_target:
    branches: [main]
    types: [opened]

jobs:
  label_customer_issues:
    runs-on: ubuntu-latest
    steps:
      - uses: dolthub/label-customer-issues@main
        with:
          repo-token: ${{ secrets.REPO_ACCESS_TOKEN }}
          issue-label: customer-issue
          pr-label: contribution
          exclude: dependabot