on:
  push:
    branches:
      - "db/test-workflow"

jobs:
  update-correctness-file:
    name: Update Correctness File
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: "db/test"
          repository: ${{ github.repository }}
          token: ${{ secrets.REPO_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
      - name: Write new correctness file
        working-directory: ./.github/scripts/sql-correctness
        env:
          CORRECTNESS_PERCENTAGE: "fake-percentage-99"
        run: |
          if [ -z "$CORRECTNESS_PERCENTAGE" ]; then
            echo "correctness percentage was empty, something went wrong"
            exit 1
          fi
          echo "$CORRECTNESS_PERCENTAGE" > current_correctness.txt
      - name: Changes detected
        id: detect-changes
        run: |
          changes=$(git status --porcelain)
          if [ ! -z "$changes" ]; then
             echo "has-changes=true" >> $GITHUB_OUTPUT
          fi
      - uses: EndBug/add-and-commit@v9.1.1
        if: ${{ steps.detect-changes.outputs.has-changes == 'true' }}
        with:
          message: ${{ format('[ga-update-correctness] SQL Correctness updated to {0}', 'fake-percentage-99') }}
          add: "./current_correctness.txt"
          cwd: "./.github/scripts/sql-correctness"
          pull: "--ff"
