on:
  workflow_dispatch:
    inputs:
      version:
        description: 'SemVer format release tag, i.e. 0.24.5'
        required: true
      email:
        description: 'email address'
        required: true
      key:
        description: 'results key'
        required: true
      pr_number:
        description: 'pull request number'
        required: false
        default: '-1'

jobs:
  trigger-benchmark-report:
    runs-on: ubuntu-18.04
    steps:
      - name: Trigger Benchmark Report
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: benchmark-report
          client-payload: '{"dolt_version": "${{ github.event.inputs.version }}", "actor": "${{ github.actor }}", "actor_email": "${{ github.event.inputs.email }}", "key":"${{ github.event.inputs.key }}", "issue_number":"${{ github.event.inputs.pr_number }}"}'
