on:
  push:
    branches:
      - 'db/test-tbd'

jobs:
  test-tbd:
    name: Test TBD Writes
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.21
      - name: Set minver TBD to version
        run: sed -i -e 's/minver:"TBD"/minver:"'"$NEW_VERSION"'"/' "$FILE"
        env:
          FILE: ${{ format('{0}/go/cmd/dolt/commands/sqlserver/yaml_config.go', github.workspace) }}
          NEW_VERSION: "test-version-0.0.1"
      - name: update minver_validation.txt
        run: go run $MAIN_GO $FILE
        env:
          MAIN_GO: ${{ format('{0}/go/utils/genminver_validation/main.go', github.workspace) }}
          FILE: ${{ format('{0}/go/cmd/dolt/commands/sqlserver/testdata/minver_validation.txt', github.workspace) }}
      - name: show minver_validation.txt diff
        run: git diff .
