on:
  workflow_dispatch:
    inputs:
      version:
        description: 'SemVer format release tag, i.e. 0.23.4'
        required: true

jobs:
  bump-dolt-version-string:
    name: Bump Version
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update dolt version
        run: sed -i 's/Version =.*/Version = "'"$VERSION"'"/' "$FILE"
        env:
          FILE: ${{ format('{0}/go/cmd/dolt/dolt.go', github.workspace) }}
          VERSION: ${{ github.event.inputs.version }}
      - uses: EndBug/add-and-commit@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          message: ${{ format('[ga-bump-release] update dolt version to {0}', github.event.inputs.version) }}
          add: ${{ format('{0}/go/cmd/dolt/dolt.go', github.workspace) }}
          cwd: "."
